set_languages("cxx17")
add_rules("mode.debug", "mode.release")

add_requires("cmake::OpenCV", {system = true, alias = "opencv", configs = {moduledirs = "/usr/local/share/cmake/opencv4"}})
add_requires("onnxruntime", {system = true, configs = {moduledirs = "/usr/local/share/cmake/onnxruntime"}})
add_requires("spdlog")

target("detector")
    set_kind("binary")
    add_includedirs("include")
    add_files("src/main.cpp")
    add_files("src/inference.cpp")
    add_packages("opencv")
    add_packages("spdlog")
    add_packages("onnxruntime")
