set_languages("cxx17")
add_rules("mode.debug", "mode.release")

add_requires("spdlog", {system = false})

add_requires("cmake::OpenCV", {system = true, alias = "opencv", configs = {moduledirs = "/usr/local/share/cmake"}})
add_requires("onnxruntime", {system = true, configs = {moduledirs = "/usr/local/share/cmake"}})
add_requires("cmake::Torch", {system = true, alias = "torch", configs = {moduledirs = "/usr/local/share/cmake"}})

add_requires("nvinfer", {system = true})
add_requires("cuda", {system = true})
-- add_requires("tensorrt", {system = true})


target("detector")
    set_kind("binary")
    add_includedirs("include")
    add_includedirs("/usr/local/cuda/include")
    add_files("src/main.cpp")
    add_files("src/utils.cpp")
    add_files("src/onnxinf.cpp")
    add_files("src/opencvinf.cpp")
    add_files("src/torchinf.cpp")
    -- add_files("src/tensorinf.cpp")
    add_packages("spdlog")
    add_packages("opencv")
    add_packages("onnxruntime")
    add_packages("torch")
    add_packages("nvinfer")
    add_packages("cuda")
